# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fly, Crash, Raise Exception
description: Random stuff from Stefano Borini
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://stefanoborini.com" # the base hostname & protocol for your site

copyright:
   name: Stefano Borini
   link: 'http://stefanoborini.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

#social
github: http://github.com/stefanoborini
analytics: UA-137605838-1

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-seo-tag]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      category: "incomplete"
      comments: true
